### ISSUE TITLE
Starting issues.

### ISSUE THREAD

**Issue by Zekodon** [cameronleger/neural-style-gui#5]
Hey guys!

I installed Java 8 (from repo), JavaFX (from repo), and extracted neural-style 1.1.1 to my desktop to make it easy. I also went ahead to install neural-style's various dependencies, Torch7, loadcaffe, cuda, cunn, and their respective dependencies.

So I extracted the latest release version to my desktop and attempted to start neural-style-gui.sh but I got this error: 

Command: `/home/zekodon/Desktop/neural-style-gui/neural-style-gui.sh`

Result: `Error: Could not find or load main class com.cameronleger.neuralstylegui.Main`

What can I do to fix this?

Thanks!

**Comment by cameronleger** [comment]
Hello, and I'm sorry that you're having this issue. From what I've read, this issue can be pretty generic so it's a little hard to track down.

I know you've said you installed it, but one common cause of this that I've seen trip users up is that JavaFX is not always included with Java in Linux distributions. Can you give me some more information on your distribution? Commands that show which Java and JavaFX packages are installed would be great, as well as an `ls -lah` of that `/home/zekodon/Desktop/neural-style-gui/` directory.

**Comment by Zekodon** [comment]
I had to reinstall torch, its dependencies to clean up the installation, but you were right. JavaFX wasn't installed. I installed it and the program launched!

**Comment by cameronleger** [comment]
Awesome! Please stay tuned, I've actually been working on 1.2.0 this past month and I hope to release it soon.
