### ISSUE TITLE
How to setup with neural-style-pt

### ISSUE THREAD

**Issue by thistleknot** [cameronleger/neural-style-gui#9]
When I attempt to run the job it asks for the location of th but I'm using torch and torchvision within python (i.e. neural-style-pt). (neural-style-pt)

**Comment by cameronleger** [comment]
Version 1.4.0 supports neural-style-pt, it should say that you need to pick _either_ th or python, so in the first file called Runner set that to your Python binary.

**Comment by thistleknot** [comment]
thank you.  I was able to get it to run with that modificaiton.

Where might I find the .caffemodel's

I found this resource?

https://gist.githubusercontent.com/ProGamerGov/ccf80be4b63f62dd6cf60db0b5c7ddbf/raw/a8c3c02bfa890f24ce90b228dfa410780850b0ab/Download%2520All%2520Neural-Style%2520Models

do I need it?

Also.  I've read about a slightly better style transfer set of algo's in...

https://github.com/EugenHotaj/pytorch-generative

How easy would it be to merge those changes with your gui?  Do I simply modify the code under neural-style-pt?

Thanks in advance.  I'm really looking forward to using this.

**Comment by cameronleger** [comment]
At a minimum you must do the setup steps from https://github.com/ProGamerGov/neural-style-pt#setup but I think that only gets you one of the models. If you want the others, then yes there's a script in there to download them. That is optional and you can leave those as they are defaulted in this program if that's fine.

I don't think my repo will work well or at all with pytorch-generate; it's designed around the CLI of either of the neural-styles that are linked, but that repo isn't similar. Hope you have fun!
